// 项目拥有者
const R_ALL = "ALL";

// 项目详情模块
const RP_PROJECT_VIEW = "PROJECT_VIEW"; // 项目基本信息详情
const RP_PROJECT_EDIT = "PROJECT_EDIT"; // 项目基本信息编辑
const RP_PROJECT_CONFIG_ADMIN = "PROJECT_CONFIG_ADMIN"; // 项目配置管理

// 访谈对象模块
const RS_SAMPLE_LIST = "SAMPLE_LIST"; // 样本列表
const RS_SAMPLE_ADD = "SAMPLE_ADD"; // 样本添加
const RS_SAMPLE_VIEW = "SAMPLE_VIEW"; // 样本详情
const RS_SAMPLE_EDIT = "SAMPLE_EDIT"; // 样本编辑
const RS_SAMPLE_DELETE = "SAMPLE_DELETE"; // 样本删除
const RS_SAMPLE_EXPORT = "SAMPLE_EXPORT"; // 样本导出
const RS_SAMPLE_PROPERTY_ADMIN = "SAMPLE_PROPERTY_ADMIN"; // 样本属性
const RS_SAMPLE_ASSIGN_ADMIN = "SAMPLE_ASSIGN_ADMIN"; // 样本分派
const RS_SAMPLE_CONTACTRECORD_ADMIN = "SAMPLE_CONTACTRECORD_ADMIN"; // 样本接触记录

// 团队模块
const RT_MEMBER_LIST = "MEMBER_LIST"; // 团队列表
const RT_MEMBER_ADD = "MEMBER_ADD"; // 团队添加
const RT_MEMBER_VIEW = "MEMBER_VIEW"; // 团队详情
const RT_MEMBER_EDIT = "MEMBER_EDIT"; // 团队编辑
const RT_MEMBER_DELETE = "MEMBER_DELETE"; // 团队删除
const RT_MEMBER_EXPORT = "MEMBER_EXPORT"; // 团队导出
const RT_MEMBER_GROUP_ADMIN = "MEMBER_GROUP_ADMIN"; // 团队分组管理
const RT_MEMBER_INVITECODE_ADMIN = "MEMBER_INVITECODE_ADMIN"; // 团队邀请码

// 访谈模块
const RI_INTERVIEW_LIST = "INTERVIEW_LIST"; // 访谈列表
const RI_INTERVIEW_ADD = "INTERVIEW_ADD"; // 访谈新建
const RI_INTERVIEW_VIEW = "INTERVIEW_VIEW"; // 访谈详情
const RI_INTERVIEW_EDIT = "INTERVIEW_EDIT"; // 访谈编辑
const RI_INTERVIEW_DELETE = "INTERVIEW_DELETE"; // 访谈删除
const RI_INTERVIEW_EXPORT = "INTERVIEW_EXPORT"; // 访谈导出
const RI_INTERVIEW_TEXT_VIEW = "INTERVIEW_TEXT_VIEW"; // 访谈文本详情
const RI_INTERVIEW_TEXT_ADD = "INTERVIEW_TEXT_ADD"; // 访谈文本录入
const RI_INTERVIEW_TEXT_EDIT = "INTERVIEW_TEXT_EDIT"; // 访谈文本编辑
const RI_INTERVIEW_TEXT_DELETE = "INTERVIEW_TEXT_DELETE"; // 访谈文本删除
const RI_INTERVIEW_TEXT_EXPORT = "INTERVIEW_TEXT_EXPORT"; // 访谈文本导出
const RI_INTERVIEW_TEXT_AUDIT = "INTERVIEW_TEXT_AUDIT"; // 访谈文本审核
const RI_INTERVIEW_VOICE_VIEW = "INTERVIEW_VOICE_VIEW"; // 访谈录音
const RI_INTERVIEW_FILE_VIEW = "INTERVIEW_FILE_VIEW"; // 访谈附件
const RI_INTERVIEW_VOICE_ADMIN = "INTERVIEW_VOICE_ADMIN"; // 访谈录音
const RI_INTERVIEW_FILE_ADMIN = "INTERVIEW_FILE_ADMIN"; // 访谈附件

// 分析模块
const RA_STAT_LIST = "STAT_LIST"; // 分析

// 监控模块
const RM_MONITOR_LIST = "MONITOR_LIST"; // 监控

export default {
  R_ALL,
  RP_PROJECT_VIEW,
  RP_PROJECT_EDIT,
  RP_PROJECT_CONFIG_ADMIN,
  RS_SAMPLE_LIST,
  RS_SAMPLE_ADD,
  RS_SAMPLE_VIEW,
  RS_SAMPLE_EDIT,
  RS_SAMPLE_DELETE,
  RS_SAMPLE_EXPORT,
  RS_SAMPLE_PROPERTY_ADMIN,
  RS_SAMPLE_ASSIGN_ADMIN,
  RS_SAMPLE_CONTACTRECORD_ADMIN,
  RT_MEMBER_LIST,
  RT_MEMBER_ADD,
  RT_MEMBER_VIEW,
  RT_MEMBER_EDIT,
  RT_MEMBER_DELETE,
  RT_MEMBER_EXPORT,
  RT_MEMBER_GROUP_ADMIN,
  RT_MEMBER_INVITECODE_ADMIN,
  RI_INTERVIEW_LIST,
  RI_INTERVIEW_ADD,
  RI_INTERVIEW_VIEW,
  RI_INTERVIEW_EDIT,
  RI_INTERVIEW_DELETE,
  RI_INTERVIEW_EXPORT,
  RI_INTERVIEW_TEXT_VIEW,
  RI_INTERVIEW_TEXT_ADD,
  RI_INTERVIEW_TEXT_EDIT,
  RI_INTERVIEW_TEXT_DELETE,
  RI_INTERVIEW_TEXT_EXPORT,
  RI_INTERVIEW_TEXT_AUDIT,
  RI_INTERVIEW_VOICE_VIEW,
  RI_INTERVIEW_FILE_VIEW,
  RI_INTERVIEW_VOICE_ADMIN,
  RI_INTERVIEW_FILE_ADMIN,
  RA_STAT_LIST,
  RM_MONITOR_LIST,
}
